version: 2.1

orbs:
  docker: circleci/docker@0.3.1

jobs:
  publish-edge:
    executor:
      name: docker/machine
      docker-layer-caching: true
    steps:
      - checkout

      - docker/build:
          name: Build base image (edge)
          path: ubuntu
          image: circleciimages/base
          tag: "$CIRCLE_SHA1"

      - docker/build:
          name: Build base image's Node variant (edge)
          path: variant-node
          image: circleciimages/base
          tag: "$CIRCLE_SHA1-node"

      - docker/check:
          name: Log into Docker Hub
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASS

      - run:
          name: Tag images (edge)
          command: |
            docker tag "circleciimages/base:$CIRCLE_SHA1" circleciimages/base:edge
            docker tag "circleciimages/base:$CIRCLE_SHA1-node" circleciimages/base:edge-node

      - docker/push:
          name: Push base image (edge)
          image: circleciimages/base
          tag: edge

      - docker/push:
          name: Push base image's Node variant (edge)
          image: circleciimages/base
          tag: edge-node

  publish-monthly:
    executor:
      name: docker/machine
      docker-layer-caching: true
    steps:
      - checkout

      - docker/build:
          name: Build base image (monthly)
          path: ubuntu
          image: circleciimages/base
          tag: "$CIRCLE_SHA1"
          extra_build_args: --pull

      - docker/build:
          name: Build base image's Node variant (monthly)
          path: variant-node
          image: circleciimages/base
          tag: "$CIRCLE_SHA1-node"
          extra_build_args: --pull

      - run:
          name: Tag images (monthly)
          command: |
            VERSION=$( date +%Y.%m )

            docker tag "circleciimages/base:$CIRCLE_SHA1" "circleciimages/base:${VERSION}"
            docker tag "circleciimages/base:$CIRCLE_SHA1-node" "circleciimages/base:${VERSION}-node"

      - docker/check:
          name: Log into Docker Hub
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASS

      - docker/push:
          name: Push base image (monthly)
          image: circleciimages/base
          tag: "$( date +%Y.%m )"

      - docker/push:
          name: Push base image's Node variant (monthly)
          image: circleciimages/base
          tag: "$( date +%Y.%m )-node"

master_filters: &master_filters
  branches:
    only: master

workflows:
  monthly-release:
    triggers:
      - schedule:
          cron: "0 0 2 * *"
          filter: *master_filters
    jobs:
      - publish-monthly:
          context: org-global
          filter: *master_filters

  main:
    jobs:
      - publish-edge:
          context: org-global
          filter: *master_filters
