version: 2.1

orbs:
  bt: circleci/build-tools@2.6.3
  cimg: cci-dev/cimg@0.0.24
  docker: circleci/docker@0.5.12

dev-filters: &dev-filters
  branches:
    ignore: master

master-filters: &master-filters
  branches:
    only: master

monthly-tag-jobs-filters: &monthly-tag-jobs-filters
  branches:
    ignore: /.*/
  tags:
    only: /monthly.*/

lint-ignore-rules: &lint-ignore-rules
  DL3007,DL3008,DL3015,SC1072,SC1090,SC2013,SC2039,SC2143,SC2162,SC2027,SC2062,SC2086

commands:
  prepare-node-dockerfile-from-template:
    parameters:
      base-org-image-tag:
        type: string
      step-name:
        type: string
    steps:
      - run:
          name: <<parameters.step-name>>
          command: |
            version=<<parameters.base-org-image-tag>>

            sed -r -e 's!%%BASE_ORG_BASE_IMAGE_BASE_TAG%%!'"$version"'!g' \
              variant-node/Dockerfile.template > variant-node/Dockerfile

      - persist_to_workspace:
          root: ~/
          paths: project

workflows:
  monthly-cron:
    triggers:
      - schedule:
          cron: "0 12 2 * *"
          filters: *master-filters
    jobs:
      - cimg/trigger-monthly-tag-jobs:
          context: image-publishing
          ssh-fingerprints: d7:ef:4c:40:d5:df:1c:54:35:4b:d0:ca:10:3c:62:e9
          filters: *master-filters

  monthly-tag-jobs:
      - docker/hadolint:
          name: lint-ubuntu-monthly
          dockerfiles: ubuntu/Dockerfile
          ignore-rules: *lint-ignore-rules
          filters: *monthly-tag-jobs-filters
          artifacts-path: ubuntu
          post-steps:
            - prepare-node-dockerfile-from-template:
                step-name: Prepare monthly Node variant Dockerfile from template
                base-org-image-tag: "cimg/base:$( date +%Y.%m )"

      - cimg/build-test-deploy:
          name: ubuntu-monthly
          context: image-publishing
          dockerfile-path: ubuntu
          image-name: cimg/base
          image-tag: "$( date +%Y.%m )"
          extra-build-args: --pull
          goss-yaml-dir-path: ubuntu
          test-suite-name: ubuntu
          deploy: true
          publish-tags: stable,latest
          filters: *monthly-tag-jobs-filters
          requires: [lint-ubuntu-monthly]

      - docker/hadolint:
          name: lint-node-monthly
          checkout: false
          attach-workspace: true
          workspace-root: ~/
          dockerfiles: variant-node/Dockerfile
          ignore-rules: *lint-ignore-rules
          filters: *monthly-tag-jobs-filters
          artifacts-path: variant-node
          requires: [lint-ubuntu-monthly]

      - cimg/build-test-deploy:
          name: node-monthly
          context: image-publishing
          checkout: false
          attach-workspace: true
          workspace-root: ~/
          dockerfile-path: variant-node
          image-name: cimg/base
          image-tag: "$( date +%Y.%m )-node"
          extra-build-args: --pull
          goss-yaml-dir-path: variant-node
          test-suite-name: variant-node
          deploy: true
          publish-tags: stable-node
          filters: *monthly-tag-jobs-filters
          requires: [ubuntu-monthly]

  commit-edge-dev:
    jobs:
      - docker/hadolint:
          name: lint-ubuntu-edge-dev
          dockerfiles: ubuntu/Dockerfile
          ignore-rules: *lint-ignore-rules
          filters: *dev-filters
          artifacts-path: ubuntu
          post-steps:
            - prepare-node-dockerfile-from-template:
                step-name: Prepare ccitest/base Node variant Dockerfile from template
                base-org-image-tag: "ccitest/base:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}"

      - cimg/build-test-deploy:
          name: ubuntu-edge-dev
          context: image-publishing
          dockerfile-path: ubuntu
          image-name: ccitest/base
          image-tag: "$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}"
          extra-build-args: --pull
          goss-yaml-dir-path: ubuntu
          test-suite-name: ubuntu
          deploy: true
          publish-tags: latest
          filters: *dev-filters
          requires: [lint-ubuntu-edge-dev]

      - docker/hadolint:
          name: lint-node-edge-dev
          checkout: false
          attach-workspace: true
          workspace-root: ~/
          dockerfiles: variant-node/Dockerfile
          ignore-rules: *lint-ignore-rules
          filters: *dev-filters
          artifacts-path: variant-node
          requires: [lint-ubuntu-edge-dev]

      - cimg/build-test-deploy:
          name: node-edge-dev
          context: image-publishing
          checkout: false
          attach-workspace: true
          workspace-root: ~/
          dockerfile-path: variant-node
          image-name: ccitest/base
          image-tag: "$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}-node"
          extra-build-args: --pull
          goss-yaml-dir-path: variant-node
          test-suite-name: variant-node
          deploy: true
          filters: *dev-filters
          requires: [ubuntu-edge-dev]

  commit-edge-master:
    jobs:
      - docker/hadolint:
          name: lint-ubuntu-edge-master
          dockerfiles: ubuntu/Dockerfile
          ignore-rules: *lint-ignore-rules
          filters: *master-filters
          artifacts-path: ubuntu
          post-steps:
            - prepare-node-dockerfile-from-template:
                step-name: Prepare edge Node variant Dockerfile from template
                base-org-image-tag: cimg/base:edge

      - cimg/build-test-deploy:
          name: ubuntu-edge-master
          context: image-publishing
          dockerfile-path: ubuntu
          image-name: cimg/base
          image-tag: edge
          extra-build-args: --pull
          goss-yaml-dir-path: ubuntu
          test-suite-name: ubuntu
          deploy: true
          publish-tags: latest
          filters: *master-filters
          requires: [lint-ubuntu-edge-master]

      - docker/hadolint:
          name: lint-node-edge-master
          checkout: false
          attach-workspace: true
          workspace-root: ~/
          dockerfiles: variant-node/Dockerfile
          ignore-rules: *lint-ignore-rules
          filters: *master-filters
          artifacts-path: variant-node
          requires: [lint-ubuntu-edge-master]

      - cimg/build-test-deploy:
          name: node-edge-master
          context: image-publishing
          checkout: false
          attach-workspace: true
          workspace-root: ~/
          dockerfile-path: variant-node
          image-name: cimg/base
          image-tag: edge-node
          extra-build-args: --pull
          goss-yaml-dir-path: variant-node
          test-suite-name: variant-node
          deploy: true
          filters: *master-filters
          requires: [ubuntu-edge-master]
