version: 2.1

orbs:
  docker: circleci/docker@0.5.0
  compare-url: iynere/compare-url@1.1.0

jobs:
  edge:
    parameters:
      publish:
        type: boolean
        default: false

    executor:
      name: docker/machine
      docker-layer-caching: true

    steps:
      - checkout

      - docker/build:
          step-name: Build cimg/base
          dockerfile: ubuntu/Dockerfile
          path: ubuntu
          image: cimg/base
          tag: "$CIRCLE_SHA1"

      - docker/build:
          step-name: Build cimg/base:node
          dockerfile: variant-node/Dockerfile
          path: variant-node
          image: cimg/base
          tag: "$CIRCLE_SHA1-node"

      - compare-url/reconstruct

      - compare-url/use:
          step-name: Check if

      - when:
          condition: <<parameters.publish>>
          steps:
            - docker/check

            - run:
                name: Tag images (edge)
                command: |
                  docker tag "cimg/base:$CIRCLE_SHA1" cimg/base:edge

                  docker tag "cimg/base:$CIRCLE_SHA1-node" cimg/base:edge-node

            - docker/push:
                step-name: Push cimg/base:edge
                image: cimg/base
                tag: edge

            - docker/push:
                step-name: Push cimg/base:edge-node
                image: cimg/base
                tag: edge-node

  monthly:
    executor:
      name: docker/machine
      docker-layer-caching: true
    steps:
      - checkout

      - docker/build:
          step-name: Build cimg/base
          dockerfile: ubuntu/Dockerfile
          path: ubuntu
          image: cimg/base
          tag: "$CIRCLE_SHA1"
          extra_build_args: --pull

      - docker/build:
          step-name: Build cimg/base:node
          dockerfile: variant-node/Dockerfile
          path: variant-node
          image: cimg/base
          tag: "$CIRCLE_SHA1-node"
          extra_build_args: --pull

      - run:
          name: Tag images (monthly)
          command: |
            VERSION=$( date +%Y.%m )

            docker tag "cimg/base:$CIRCLE_SHA1" "cimg/base:${VERSION}"

            docker tag "cimg/base:$CIRCLE_SHA1-node" "cimg/base:${VERSION}-node"

      - docker/check

      - docker/push:
          step-name: Push cimg/base:year.month
          image: cimg/base
          tag: "$( date +%Y.%m )"

      - docker/push:
          step-name: Push cimg/base:year.month-node
          image: cimg/base
          tag: "$( date +%Y.%m )-node"

dev_filters: &dev_filters
  branches:
    ignore: master

master_filters: &master_filters
  branches:
    only: master

workflows:
  cron-monthly:
    triggers:
      - schedule:
          cron: "0 0 2 * *"
          filters: *master_filters
    jobs:
      - monthly:
          context: image-publishing
          filters: *master_filters

  commit-edge:
    jobs:
      - edge:
          name: edge-test
          filters: *dev_filters

      - edge:
          name: edge-test-publish
          context: image-publishing
          publish: true
          filters: *master_filters
