version: 2.1

orbs:
  docker: circleci/docker@0.3.1

jobs:
  edge:
    parameters:
      publish:
        type: boolean
        default: false

    executor:
      name: docker/machine
      docker-layer-caching: true
    steps:
      - checkout

      - docker/build:
          dockerfile: ubuntu/Dockerfile
          path: ubuntu
          image: circleciimages/base
          tag: "$CIRCLE_SHA1"

      - docker/build:
          dockerfile: variant-node/Dockerfile
          path: variant-node
          image: circleciimages/base
          tag: "$CIRCLE_SHA1-node"

      - when:
          condition: <<parameters.publish>>
          steps:
            - docker/check

            - run:
                name: Tag images (edge)
                command: |
                  docker tag "circleciimages/base:$CIRCLE_SHA1" circleciimages/base:edge

                  docker tag "circleciimages/base:$CIRCLE_SHA1-node" circleciimages/base:edge-node

            - docker/push:
                image: circleciimages/base
                tag: edge

            - docker/push:
                image: circleciimages/base
                tag: edge-node

  monthly:
    executor:
      name: docker/machine
      docker-layer-caching: true
    steps:
      - checkout

      - docker/build:
          dockerfile: ubuntu/Dockerfile
          path: ubuntu
          image: circleciimages/base
          tag: "$CIRCLE_SHA1"
          extra_build_args: --pull

      - docker/build:
          dockerfile: variant-node/Dockerfile
          path: variant-node
          image: circleciimages/base
          tag: "$CIRCLE_SHA1-node"
          extra_build_args: --pull

      - run:
          name: Tag images (monthly)
          command: |
            VERSION=$( date +%Y.%m )

            docker tag "circleciimages/base:$CIRCLE_SHA1" "circleciimages/base:${VERSION}"

            docker tag "circleciimages/base:$CIRCLE_SHA1-node" "circleciimages/base:${VERSION}-node"

      - docker/check

      - docker/push:
          image: circleciimages/base
          tag: "$( date +%Y.%m )"

      - docker/push:
          image: circleciimages/base
          tag: "$( date +%Y.%m )-node"

dev_filters: &dev_filters
  branches:
    ignore: master

master_filters: &master_filters
  branches:
    only: master

workflows:
  monthly-release:
    triggers:
      - schedule:
          cron: "0 0 2 * *"
          filters: *master_filters
    jobs:
      - monthly:
          context: image-publishing
          filters: *master_filters

  main:
    jobs:
      - edge:
          name: edge-test
          filters: *dev_filters

      - edge:
          name: edge-test-publish
          context: image-publishing
          publish: true
          filters: *master_filters
